CREATE TABLE users
(
    id serial not null unique,
    name varchar(255) not null,
    email varchar(255) not null unique,
    password_hash varchar(255) not null
);

CREATE TABLE books
(
    id serial not null unique,
    name varchar(255) not null,
    face_path varchar(255) not null unique,
    last_page int not null UNIQUE,
    path VARCHAR(255) not null unique,
    description VARCHAR(255) NOT NULL

);

CREATE TABLE categories
(
    id serial not null UNIQUE,
    name varchar(255) not null
);

CREATE TABLE users_books
(
    id serial not null unique,
    from_id int not null UNIQUE,
    to_id int not null UNIQUE 
);

CREATE TABLE books_categories
(
    id serial not null unique,
    from_id int not null UNIQUE,
    to_id int not null UNIQUE 
);

INSERT INTO categories (name) VALUES
("Golang"),
("C++"),
("C"),
("CSharp"),
("Rust"),
("Python"),
("Java"),
("JavaScript"),
("TypeScript"),
("Swift"),
("Kotlin"),
("PHP"),
("Ruby"),
("Objective-C"),
("SQL"),
("NoSQL"),
("PostgreSQL"),
("MongoDB"),
("Redis"),
("MySQL"),
("SQLite"),
("Docker"),
("Kubernetes"),
("Linux"),
("DevOps"),
("CI/CD"),
("Cloud Computing"),
("AWS"),
("Azure"),
("Google Cloud Platform"),
("Microservices"),
("API Development"),
("REST API"),
("GraphQL"),
("Software Architecture"),
("System Design"),
("Algorithms"),
("Data Structures"),
("Artificial Intelligence"),
("Machine Learning"),
("Deep Learning"),
("Neural Networks"),
("Data Science"),
("Big Data"),
("Data Engineering"),
("Blockchain"),
("Cryptography"),
("Cybersecurity"),
("Penetration Testing"),
("Networking"),
("Operating Systems"),
("Computer Science"),
("Mathematics for CS"),
("Discrete Mathematics"),
("Compilers"),
("Programming Languages Theory"),
("Functional Programming"),
("Object-Oriented Programming"),
("Test-Driven Development"),
("Unit Testing"),
("Integration Testing"),
("QA / Automation Testing"),
("Mobile Development"),
("iOS Development"),
("Android Development"),
("Flutter"),
("React Native"),
("Web Development"),
("Frontend Development"),
("Backend Development"),
("Fullstack Development"),
("HTML/CSS"),
("Sass/SCSS"),
("React.js"),
("Next.js"),
("Vue.js"),
("Nuxt.js"),
("Angular"),
("Svelte"),
("Node.js"),
("Express.js"),
("NestJS"),
("Django"),
("Flask"),
("Spring Boot"),
("ASP.NET Core"),
("Game Development"),
("Unity"),
("Unreal Engine"),
("VR/AR Development"),
("Embedded Systems"),
("IoT (Internet of Things)"),
("Robotics"),
("Quantum Computing"),
("Ethical Hacking"),
("Information Security"),
("Cloud Security"),
("Networking Security"),
("Agile Methodologies"),
("Scrum"),
("Kanban"),
("Project Management"),
("Product Management"),
("UX/UI Design"),
("Design Patterns"),
("Clean Code"),
("Refactoring"),
("Software Testing"),
("Performance Optimization"),
("Low-Level Programming"),
("High-Performance Computing"),
("Parallel Programming"),
("Concurrency"),
("Open Source Development"),
("Technical Writing"),
("Career Development in IT"),
("Startups and Entrepreneurship"),
("Leadership in Tech");


